package yoshikihigo.clonegear.gui.view;

import java.text.DecimalFormat;

public interface ViewScale {

	int VISUAL_CLONEPAIRLISTVIEW_COL_MIN_WIDTH = 140;
	int VISUAL_CLONEPAIRLISTVIEW_COL_MAX_WIDTH = 140;
	int VISUAL_CLONEPAIRLISTVIEW_MIN_WIDTH = VISUAL_CLONEPAIRLISTVIEW_COL_MIN_WIDTH * 2;
	int VISUAL_CLONEPAIRLISTVIEW_MAX_WIDTH = VISUAL_CLONEPAIRLISTVIEW_COL_MAX_WIDTH * 2;

	int VISUAL_FILELISTVIEW_ID_COL_MIN_WIDTH = 60;
	int VISUAL_FILELISTVIEW_ID_COL_MAX_WIDTH = 60;
	int VISUAL_FILELISTVIEW_LOC_COL_MIN_WIDTH = 60;
	int VISUAL_FILELISTVIEW_LOC_COL_MAX_WIDTH = 60;
	int VISUAL_FILELISTVIEW_TOC_COL_MIN_WIDTH = 60;
	int VISUAL_FILELISTVIEW_TOC_COL_MAX_WIDTH = 60;
	int VISUAL_FILELISTVIEW_NOC_COL_MIN_WIDTH = 60;
	int VISUAL_FILELISTVIEW_NOC_COL_MAX_WIDTH = 60;
	int VISUAL_FILELISTVIEW_ROC_COL_MIN_WIDTH = 60;
	int VISUAL_FILELISTVIEW_ROC_COL_MAX_WIDTH = 60;
	int VISUAL_FILELISTVIEW_NOF_COL_MIN_WIDTH = 60;
	int VISUAL_FILELISTVIEW_NOF_COL_MAX_WIDTH = 60;
	int VISUAL_FILELISTVIEW_FILENAME_COL_MIN_WIDTH = 120;
	int VISUAL_FILELISTVIEW_FILENAME_COL_MAX_WIDTH = 120;
	int VISUAL_FILELISTVIEW_MIN_WIDTH = VISUAL_FILELISTVIEW_FILENAME_COL_MIN_WIDTH
			+ VISUAL_FILELISTVIEW_LOC_COL_MIN_WIDTH
			+ VISUAL_FILELISTVIEW_TOC_COL_MIN_WIDTH
			+ VISUAL_FILELISTVIEW_NOC_COL_MIN_WIDTH
			+ VISUAL_FILELISTVIEW_ROC_COL_MIN_WIDTH
			+ VISUAL_FILELISTVIEW_NOF_COL_MIN_WIDTH;
	int VISUAL_FILELISTVIEW_MAX_WIDTH = VISUAL_FILELISTVIEW_FILENAME_COL_MAX_WIDTH
			+ VISUAL_FILELISTVIEW_LOC_COL_MAX_WIDTH
			+ VISUAL_FILELISTVIEW_TOC_COL_MAX_WIDTH
			+ VISUAL_FILELISTVIEW_NOC_COL_MAX_WIDTH
			+ VISUAL_FILELISTVIEW_ROC_COL_MAX_WIDTH
			+ VISUAL_FILELISTVIEW_NOF_COL_MAX_WIDTH;

	int QUANTITATIVE_GROUPLISTVIEW_ID_COL_MIN_WIDTH = 40;
	int QUANTITATIVE_GROUPLISTVIEW_ID_COL_MAX_WIDTH = 40;
	int QUANTITATIVE_GROUPLISTVIEW_NOF_COL_MIN_WIDTH = 60;
	int QUANTITATIVE_GROUPLISTVIEW_NOF_COL_MAX_WIDTH = 60;
	int QUANTITATIVE_GROUPLISTVIEW_LOC_COL_MIN_WIDTH = 60;
	int QUANTITATIVE_GROUPLISTVIEW_LOC_COL_MAX_WIDTH = 60;
	int QUANTITATIVE_GROUPLISTVIEW_TOC_COL_MIN_WIDTH = 60;
	int QUANTITATIVE_GROUPLISTVIEW_TOC_COL_MAX_WIDTH = 60;
	int QUANTITATIVE_GROUPLISTVIEW_NOC_COL_MIN_WIDTH = 70;
	int QUANTITATIVE_GROUPLISTVIEW_NOC_COL_MAX_WIDTH = 70;
	int QUANTITATIVE_GROUPLISTVIEW_ROC_COL_MIN_WIDTH = 80;
	int QUANTITATIVE_GROUPLISTVIEW_ROC_COL_MAX_WIDTH = 80;
	int QUANTITATIVE_GROUPLISTVIEW_MIN_WIDTH = QUANTITATIVE_GROUPLISTVIEW_ID_COL_MIN_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_NOF_COL_MIN_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_LOC_COL_MIN_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_TOC_COL_MIN_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_NOC_COL_MIN_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_ROC_COL_MIN_WIDTH;
	int QUANTITATIVE_GROUPLISTVIEW_MAX_WIDTH = QUANTITATIVE_GROUPLISTVIEW_ID_COL_MAX_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_NOF_COL_MAX_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_LOC_COL_MAX_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_TOC_COL_MAX_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_NOC_COL_MAX_WIDTH
			+ QUANTITATIVE_GROUPLISTVIEW_ROC_COL_MAX_WIDTH;

	int QUANTITATIVE_RELATEDGROUPLISTVIEW_ID_COL_MIN_WIDTH = 60;
	int QUANTITATIVE_RELATEDGROUPLISTVIEW_ID_COL_MAX_WIDTH = 60;
	int QUANTITATIVE_RELATEDGROUPLISTVIEW_NOC_COL_MIN_WIDTH = 60;
	int QUANTITATIVE_RELATEDGROUPLISTVIEW_NOC_COL_MAX_WIDTH = 60;
	int QUANTITATIVE_RELATEDGROUPLISTVIEW_ROC_COL_MIN_WIDTH = 50;
	int QUANTITATIVE_RELATEDGROUPLISTVIEW_ROC_COL_MAX_WIDTH = 50;

	int QUANTITATIVE_FILELISTVIEW_FILENAME_COL_MIN_WIDTH = VISUAL_FILELISTVIEW_FILENAME_COL_MIN_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_FILENAME_COL_MAX_WIDTH = VISUAL_FILELISTVIEW_FILENAME_COL_MAX_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_LOC_COL_MIN_WIDTH = VISUAL_FILELISTVIEW_LOC_COL_MIN_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_LOC_COL_MAX_WIDTH = VISUAL_FILELISTVIEW_LOC_COL_MAX_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_TOC_COL_MIN_WIDTH = VISUAL_FILELISTVIEW_TOC_COL_MIN_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_TOC_COL_MAX_WIDTH = VISUAL_FILELISTVIEW_TOC_COL_MAX_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_NOC_COL_MIN_WIDTH = VISUAL_FILELISTVIEW_NOC_COL_MIN_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_NOC_COL_MAX_WIDTH = VISUAL_FILELISTVIEW_NOC_COL_MAX_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_ROC_COL_MIN_WIDTH = VISUAL_FILELISTVIEW_ROC_COL_MIN_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_ROC_COL_MAX_WIDTH = VISUAL_FILELISTVIEW_ROC_COL_MAX_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_NOF_COL_MIN_WIDTH = VISUAL_FILELISTVIEW_NOF_COL_MIN_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_NOF_COL_MAX_WIDTH = VISUAL_FILELISTVIEW_NOF_COL_MAX_WIDTH;

	int QUANTITATIVE_FILELISTVIEW_MIN_WIDTH = VISUAL_FILELISTVIEW_MIN_WIDTH;
	int QUANTITATIVE_FILELISTVIEW_MAX_WIDTH = VISUAL_FILELISTVIEW_MAX_WIDTH;

	int QUANTITATIVE_RELATEDFILELISTVIEW_FILENAME_COL_MIN_WIDTH = QUANTITATIVE_FILELISTVIEW_FILENAME_COL_MIN_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_FILENAME_COL_MAX_WIDTH = QUANTITATIVE_FILELISTVIEW_FILENAME_COL_MAX_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_LOC_COL_MIN_WIDTH = QUANTITATIVE_FILELISTVIEW_LOC_COL_MIN_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_LOC_COL_MAX_WIDTH = QUANTITATIVE_FILELISTVIEW_LOC_COL_MAX_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_TOC_COL_MIN_WIDTH = QUANTITATIVE_FILELISTVIEW_TOC_COL_MIN_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_TOC_COL_MAX_WIDTH = QUANTITATIVE_FILELISTVIEW_TOC_COL_MAX_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_NOC_COL_MIN_WIDTH = QUANTITATIVE_FILELISTVIEW_NOC_COL_MIN_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_NOC_COL_MAX_WIDTH = QUANTITATIVE_FILELISTVIEW_NOC_COL_MAX_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_ROC_COL_MIN_WIDTH = QUANTITATIVE_FILELISTVIEW_ROC_COL_MIN_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_ROC_COL_MAX_WIDTH = QUANTITATIVE_FILELISTVIEW_ROC_COL_MAX_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_NOF_COL_MIN_WIDTH = QUANTITATIVE_FILELISTVIEW_NOF_COL_MIN_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_NOF_COL_MAX_WIDTH = QUANTITATIVE_FILELISTVIEW_NOF_COL_MAX_WIDTH;

	int QUANTITATIVE_RELATEDFILELISTVIEW_MIN_WIDTH = QUANTITATIVE_FILELISTVIEW_MIN_WIDTH;
	int QUANTITATIVE_RELATEDFILELISTVIEW_MAX_WIDTH = QUANTITATIVE_FILELISTVIEW_MAX_WIDTH;

	int QUANTITATIVE_CLONELISTVIEW_LOCATION_COL_MIN_WIDTH = 110;
	int QUANTITATIVE_CLONELISTVIEW_LOCATION_COL_MAX_WIDTH = 110;
	int QUANTITATIVE_CLONELISTVIEW_LENGTH_COL_MIN_WIDTH = 50;
	int QUANTITATIVE_CLONELISTVIEW_LENGTH_COL_MAX_WIDTH = 50;
	int QUANTITATIVE_CLONELISTVIEW_DISPERSIVITY_COL_MIN_WIDTH = 80;
	int QUANTITATIVE_CLONELISTVIEW_DISPERSIVITY_COL_MAX_WIDTH = 80;
	int QUANTITATIVE_CLONELISTVIEW_EQUIVALENCE_COL_MIN_WIDTH = 80;
	int QUANTITATIVE_CLONELISTVIEW_EQUIVALENCE_COL_MAX_WIDTH = 80;
	int QUANTITATIVE_CLONELISTVIEW_MIN_WIDTH = QUANTITATIVE_CLONELISTVIEW_LOCATION_COL_MIN_WIDTH
			+ QUANTITATIVE_CLONELISTVIEW_LENGTH_COL_MIN_WIDTH
			+ QUANTITATIVE_CLONELISTVIEW_DISPERSIVITY_COL_MIN_WIDTH
			+ QUANTITATIVE_CLONELISTVIEW_EQUIVALENCE_COL_MIN_WIDTH;
	int QUANTITATIVE_CLONELISTVIEW_MAX_WIDTH = QUANTITATIVE_CLONELISTVIEW_LOCATION_COL_MAX_WIDTH
			+ QUANTITATIVE_CLONELISTVIEW_LENGTH_COL_MAX_WIDTH
			+ QUANTITATIVE_CLONELISTVIEW_DISPERSIVITY_COL_MAX_WIDTH
			+ QUANTITATIVE_CLONELISTVIEW_EQUIVALENCE_COL_MAX_WIDTH;

	int METRIC_METRICVIEW_MIN_WIDTH = 300;
	int METRIC_METRICVIEW_INIT_WIDTH = 550;

	int METRIC_CLONESETLISTVIEW_ID_COL_MIN_WIDTH = 40;
	int METRIC_CLONESETLISTVIEW_ID_COL_MAX_WIDTH = 40;
	int METRIC_CLONESETLISTVIEW_RAD_COL_MIN_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_RAD_COL_MAX_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_LEN_COL_MIN_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_LEN_COL_MAX_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_RNR_COL_MIN_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_RNR_COL_MAX_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_NIF_COL_MIN_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_NIF_COL_MAX_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_POP_COL_MIN_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_POP_COL_MAX_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_DFL_COL_MIN_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_DFL_COL_MAX_WIDTH = 50;
	int METRIC_CLONESETLISTVIEW_MIN_WIDTH = METRIC_CLONESETLISTVIEW_ID_COL_MIN_WIDTH
			+ METRIC_CLONESETLISTVIEW_RAD_COL_MIN_WIDTH
			+ METRIC_CLONESETLISTVIEW_LEN_COL_MIN_WIDTH
			+ METRIC_CLONESETLISTVIEW_RNR_COL_MIN_WIDTH
			+ METRIC_CLONESETLISTVIEW_NIF_COL_MIN_WIDTH
			+ METRIC_CLONESETLISTVIEW_POP_COL_MIN_WIDTH
			+ METRIC_CLONESETLISTVIEW_DFL_COL_MIN_WIDTH;
	int METRIC_CLONESETLISTVIEW_MAX_WIDTH = METRIC_CLONESETLISTVIEW_ID_COL_MAX_WIDTH
			+ METRIC_CLONESETLISTVIEW_RAD_COL_MAX_WIDTH
			+ METRIC_CLONESETLISTVIEW_LEN_COL_MAX_WIDTH
			+ METRIC_CLONESETLISTVIEW_RNR_COL_MAX_WIDTH
			+ METRIC_CLONESETLISTVIEW_NIF_COL_MAX_WIDTH
			+ METRIC_CLONESETLISTVIEW_POP_COL_MAX_WIDTH
			+ METRIC_CLONESETLISTVIEW_DFL_COL_MAX_WIDTH;

	int METRIC_CLONELISTVIEW_LENGTH_COL_MIN_WIDTH = 100;
	int METRIC_CLONELISTVIEW_LENGTH_COL_MAX_WIDTH = 100;
	int METRIC_CLONELISTVIEW_DISPERSIVITY_COL_MIN_WIDTH = 100;
	int METRIC_CLONELISTVIEW_DISPERSIVITY_COL_MAX_WIDTH = 100;
	int METRIC_CLONELISTVIEW_EQUIVALENCE_COL_MIN_WIDTH = 100;
	int METRIC_CLONELISTVIEW_EQUIVALENCE_COL_MAX_WIDTH = 100;

	DecimalFormat ROC_FORMAT = new DecimalFormat("##0.0");
}
