package yoshikihigo.clonegear.gui.view;


import java.awt.Color;


public interface ViewColors {

    Color DEFAULT_TABLEVIEW_SELECTION_BACKGROUND_COLOR = new Color(90, 90, 180, 63);

    Color DEFAULT_TABLEVIEW_PRACTICAL_BACKGROUND_COLOR = Color.white;

    Color DEFAULT_TABLEVIEW_UNINTERESTING_BACKGROUND_COLOR = new Color(222, 222, 222);

    Color DEFAULT_TABLEVIEW__FOREGROUND_COLOR = Color.black;

    Color SCATTERPLOT_BACKGROUND_COLOR = Color.white;

    Color SCATTERPLOT_FILTERIN_CLONEPAIR_COLOR = Color.black;

    Color SCATTERPLOT_FILTEROUT_CLONEPAIR_COLOR = Color.blue;

    Color SCATTERPLOT_SELECTED_CLONEPAIR_COLOR = Color.green;

    Color SCATTERPLOT_SELECTED_AREA_COLOR = new Color(255, 0, 0, 125);

    Color SCATTERPLOT_FRAME_COLOR = Color.black;

    Color SCATTERPLOT_FILE_SEPARATOR_COLOR = Color.lightGray;

    Color SCATTERPLOT_GROUP_SEPARATOR_COLOR = Color.darkGray;

    Color SCATTERPLOT_SPLIT_LINE_COLOR = Color.black;

    Color SCATTERPLOT_STRING_COLOR = Color.black;

    Color SCATTERPLOT_DIAGONAL_COLOR = Color.black;

    Color SCATTERPLOT_COORDINATE_LINE_COLOR = new Color(0, 0, 255, 192);

    Color navy = new Color(12, 43, 116); // 紺

    Color palePurple = new Color(128, 128, 192); // 薄紫

    Color seethroughPurple = new Color(90, 90, 180, 63); // 半透明紫

    Color moreSeethroughPurple = new Color(90, 90, 180, 20); // もっと半透明紫

    Color seethroughRed = new Color(255, 0, 0, 200); // 半透明赤

    Color moreSeethroughRed = new Color(255, 0, 0, 125); // もっと半透明赤

    Color lightRed = new Color(240, 70, 100); // 薄赤

    Color orange = new Color((int) (0.2 * Color.red.getRed() + 0.8 * Color.orange.getRed()),
            (int) (0.2 * Color.red.getGreen() + 0.8 * Color.orange.getGreen()),
            (int) (0.2 * Color.red.getBlue() + 0.8 * Color.orange.getBlue())); // オレンジ

    // Table
    Color TABLE_SELECTION_COLOR = seethroughPurple;

    Color TABLE_UNSELECTION_COLOR = Color.white;

    Color TABLE_FOREGROUND_COLOR = Color.black;

    Color TABLE_SELECTION_COLOR2 = seethroughPurple;

    Color TABLE_UNSELECTION_COLOR2 = Color.lightGray;

    // BarGraph
    Color BARGRAPH_BG_COLOR = Color.white;

    Color BARGRAPH_FRAME_COLOR = Color.lightGray;

    Color BARGRAPH_AXIS_COLOR = Color.black;

    Color BARGRAPH_SCALE_COLOR = Color.lightGray;

    Color BARGRAPH_SCALE_LABEL_COLOR = Color.black;

    Color BARGRAPH_DATA_FRA_COLOR_RST = navy;

    Color BARGRAPH_DATA_COLOR_RST = palePurple;

    Color BARGRAPH_DATA_COLOR_RST_SELF = Color.lightGray;

    Color BARGRAPH_DATA_FRA_COLOR_RSA = Color.red;

    Color BARGRAPH_DATA_COLOR_RSA = lightRed;

    Color VISUAL_CLONEPAIRLISTVIEW_SELECTION_BACKGROUND_COLOR = DEFAULT_TABLEVIEW_SELECTION_BACKGROUND_COLOR;

    Color VISUAL_CLONEPAIRLISTVIEW_PRACTICAL_BACKGROUND_COLOR = DEFAULT_TABLEVIEW_PRACTICAL_BACKGROUND_COLOR;

    Color VISUAL_CLONEPAIRLISTVIEW_UNINTERESTING_BACKGROUND_COLOR = DEFAULT_TABLEVIEW_UNINTERESTING_BACKGROUND_COLOR;

    Color VISUAL_CLONEPAIRLISTVIEW_FOREGROUND_COLOR = DEFAULT_TABLEVIEW__FOREGROUND_COLOR;

    Color VISUAL_HORIZONTAL_COLOR = new Color(255, 0, 0, 125);

    Color VISUAL_VERTICAL_COLOR = new Color(0, 200, 255, 125);

    Color VISUAL_FILELISTVIEW_SELECTED_FOREGROUND_COLOR = Color.black;

    Color VISUAL_FILELISTVIEW_UNSELECTED_FOREGROUND_COLOR = Color.black;

    Color VISUAL_FILELISTVIEW_UNSELECTED_BACKGROUND_COLOR = Color.white;

    Color VISUAL_DIRECTORYTREE_SELECTED_FOREGROUND_COLOR = Color.black;

    Color VISUAL_DIRECTORYTREE_UNSELECTED_FOREGROUND_COLOR = Color.black;

    Color VISUAL_DIRECTORYTREE_UNSELECTED_BACKGROUND_COLOR = Color.white;

    Color VISUAL_SOURCECODEVIEW_UNINTERESTING_CODECLONE_COLOR = new Color(180, 180, 180, 125);

    Color VISUAL_SOURCECODEVIEW_LANG_TOKEN_COLOR = new Color(12, 43, 116);

    Color VISUAL_SOURCECODEVIEW_LINENUM_COLOR = new Color(0, 100, 0);

    Color QUANTITATIVE_RELATEDFILELISTVIEW_SELECTION_BACKGROUND_COLOR = DEFAULT_TABLEVIEW_SELECTION_BACKGROUND_COLOR;

    Color QUANTITATIVE_RELATEDFILELISTVIEW_PRACTICAL_BACKGROUND_COLOR = DEFAULT_TABLEVIEW_PRACTICAL_BACKGROUND_COLOR;

    Color QUANTITATIVE_RELATEDFILELISTVIEW_UNINTERESTING_BACKGROUND_COLOR = DEFAULT_TABLEVIEW_UNINTERESTING_BACKGROUND_COLOR;

    Color QUANTITATIVE_RELATEDFILELISTVIEW_FOREGROUND_COLOR = DEFAULT_TABLEVIEW__FOREGROUND_COLOR;

    Color QUANTITATIVE_CODEFRAGMENTVIEW_SELECTION_COLOR = new Color(90, 90, 180, 63);

    Color QUANTITATIVE_CODEFRAGMENTVIEW_UNSELECTION_COLOR = Color.white;

    Color QUANTITATIVE_CODEFRAGMENTVIEW_UNSELECTION_COLOR2 = new Color(222, 222, 222);

    Color QUANTITATIVE_CODEFRAGMENTVIEW_FOREGROUND_COLOR = Color.black;

    Color QUANTITATIVE_SOURCECODEVIEW_DENSE_CLONE_COLOR = new Color(0, 0, 200, 50);

    Color QUANTITATIVE_SOURCECODEVIEW_MIDDLE_CLONE_COLOR = new Color(0, 200, 0, 50);

    Color QUANTITATIVE_SOURCECODEVIEW_SCATTERED_CLONE_COLOR = new Color(200, 0, 0, 50);

    Color QUANTITATIVE_SOURCECODEVIEW_UNINTERESTING_CLONE_COLOR = new Color(180, 180, 180, 125);

    Color QUANTITATIVE_SOURCECODEVIEW_LANG_TOKEN_COLOR = new Color(12, 43, 116);

    Color QUANTITATIVE_SOURCECODEVIEW_LINENUM_COLOR = new Color(0, 100, 0);

    Color METRIC_GRAPH_BACKGROUND_COLOR = Color.white;

    Color METRIC_GRAPH_STATUS_COLOR = Color.black;

    Color METRIC_GRAPH_FRAME_COLOR = Color.black;

    Color METRIC_GRAPH_AXIS_COLOR = Color.black;

    Color METRICS_AXIS_SCALE_COLOR = Color.black;

    Color METRICS_AXIS_TITLE_COLOR = Color.black;

    Color METRICS_AXIS_LABEL_COLOR = Color.black;

    Color METRICS_FILTER_AREA_ON_COLOR = new Color(90, 90, 180, 63);;

    Color METRICS_FILTER_AREA_OFF_COLOR = new Color(90, 90, 180, 20);

    Color METRICS_UN_SELECTED_DATA_COLOR = Color.lightGray;

    Color METRICS_SELECTED_DATA_COLOR = Color.red;

    Color METRICS_GRADUATION_TOP_COLOR = Color.red;

    Color METRICS_GRADUATION_BOTTOM_COLOR = Color.lightGray;
}
